// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD63gw5ZXRM5UqqVWfnLa4L8Dg1T9i-I48',
    appId: '1:930132494875:web:1c46ab5bcc49b6b44a86be',
    messagingSenderId: '930132494875',
    projectId: 'catchit-firebase',
    authDomain: 'catchit-firebase.firebaseapp.com',
    storageBucket: 'catchit-firebase.appspot.com',
    measurementId: 'G-KQQ17RMXZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkGHm90OhpyhqPDZrf9UVL_CA6fxHKIWw',
    appId: '1:930132494875:android:f69e7c97289ee6ac4a86be',
    messagingSenderId: '930132494875',
    projectId: 'catchit-firebase',
    storageBucket: 'catchit-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3rLzOjjdLKpvQMX781cLojFWCg9TOk98',
    appId: '1:930132494875:ios:32d28f9419c4c9604a86be',
    messagingSenderId: '930132494875',
    projectId: 'catchit-firebase',
    storageBucket: 'catchit-firebase.appspot.com',
    iosClientId:
        '930132494875-5ng5d6ugg6dqlmflvt2llg2j7gki6tbk.apps.googleusercontent.com',
    iosBundleId: 'com.catchit.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3rLzOjjdLKpvQMX781cLojFWCg9TOk98',
    appId: '1:930132494875:ios:32d28f9419c4c9604a86be',
    messagingSenderId: '930132494875',
    projectId: 'catchit-firebase',
    storageBucket: 'catchit-firebase.appspot.com',
    iosClientId:
        '930132494875-5ng5d6ugg6dqlmflvt2llg2j7gki6tbk.apps.googleusercontent.com',
    iosBundleId: 'com.catchit.app',
  );
}
